name: sync unreal repo

on: 
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Create Pull Request in Target Repo
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        repository: puerts/Puerts
        branch: auto-sync
        path: unreal/Puerts
        commit-message: "Sync from upstream"
        title: "Auto-sync changes"
        body: "Automated sync from source repository"
