name: sync unreal repo

on: 
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Filter directory
      run: |
        sudo apt install git-filter-repo
        git filter-repo --subdirectory-filter unreal/Puerts/ --force
        git remote add origin git@github.com:puerts/Puerts.git

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        base: master 